apiVersion : apps/v1
kind: Deployment
metadata:
  name: yingmanjitestdevopseureka 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yingmanjitestdevopseureka
  template:
    metadata:
      labels:
        app: yingmanjitestdevopseureka
    spec:
      containers:
        - name: yingmanjitestdevopseureka
          image: yingmanjicr.azurecr.io/yingmanjitestdevopseureka
          ports:
          - containerPort: 7070
